export const BACKEND_URL = process.env.BACKEND_URL || "https://can-you-negotiate-agent.onrender.com";

export const DISPATCH_INTERVAL_MS = 1200;
export const DISPATCH_PROGRESS_MAX = 95;
export const INITIAL_STRESS = 90;
export const ESCALATION_DISPLAY_MS = 5000;
export const AUDIO_CONTEXT_CLOSE_DELAY_MS = 300;
export const MID_CALL_DROP_TIMEOUT_MS = 4000;
export const INITIAL_DISPATCH_TIMEOUT_MS = 120000;
export const NETWORK_STALL_TIMEOUT_MS = 45000;
export const CUSTOM_PERSONA_DEBOUNCE_MS = 800;
export const ROOM_NAME_RANDOM_MAX = 10000;
export const LIVEKIT_EMPTY_TIMEOUT_SECONDS = 10 * 60;
export const SURRENDER_THRESHOLD_PERCENT = 20;
export const SURRENDER_LABEL_OFFSET_PERCENT = 22;

export const DISPATCH_MESSAGES = [
  "ESTABLISHING SECURE CHANNEL...",
  "PATCHING INTO LIVE AUDIO FEED...",
  "TRIANGULATING SUBJECT LOCATION...",
  "ROUTING ENCRYPTED COMMS LINK...",
  "OPENING NEGOTIATION LINE...",
  "SUBJECT LOCATED // CONNECTING...",
] as const;
